import collections
"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"
 
"""
def findTheDifference(s, t):
    if len(s) > 0:
        counter = collections.Counter(s)
        for ch in t:
            if ch in counter and counter[ch] > 0:
                counter[ch] -= 1
            else:
                return ch
    else:
        return t


print(findTheDifference(s = "abcd", t = "abcde"))
    